### ISSUE TITLE
How to get pageContext and webparts properties in Aurelia app?

### ISSUE THREAD

**Issue by bartkusters** [magnusdanielson/spfx-aurelia#1]
Hi Magnus,

Great example, but I was wondering how I can connect to SharePoint / how I can access the page context from within the Aurelia app?

Also wondering how to access the webparts configuration/properties (IHelloWorldWebPartProps)?

If you could help with that, then that would be great.

Thanks,

Bart

**Comment by ma3yta** [comment]
@bartkusters maybe this link helps you https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-existing-javascript-libraries

**Comment by magnusdanielson** [comment]
@bartkusters Sorry for the late reply. I use the dependency injection feature in Aurelia.

`aurelia.container.registerInstance("WebPartContext", this.context);`

I my render method I store looks like below. Notice the line with registerInstance


    public render(): void 
    {
    
        this.domElement.innerHTML = '<div id="${this.instanceId}" class="${this.instanceId}"  >Loading...</div>';

        require(['aurelia-bootstrapper'],(au) =>
        {
            au.bootstrap((aurelia: Aurelia) =>
            {
                aurelia.use
                .standardConfiguration()
                .developmentLogging();
                
                var el = document.getElementById(this.instanceId);
                aurelia.start().then(() => {
                    aurelia.container.registerInstance("WebPartContext", this.context);
                    aurelia.setRoot(PLATFORM.moduleName('webparts/documentList/document'),el);
                });
                }
            );
        
        });
    }

And then you can inject the context anywhere you like, see the code below.

    import WebPartContext from '@microsoft/sp-webpart-base/lib/core/WebPartContext';
    
    @inject("WebPartContext")
    export class documentlist 
    {
    
        public webpartContext: WebPartContext;
    
        constructor(webpartContext: WebPartContext) 
        {
            this.webpartContext = webpartContext;
        }
    }

**Comment by bartkusters** [comment]
@magnusdanielson thank you very much, and no worries for the late response, much appreciate your effort to response.
